# =============================================================================
# Publish-WeeklyPost.ps1
# Creates a new branch, writes the bilingual weekly post files (EN + FR),
# commits them, pushes to GitHub, and opens a Pull Request via the GitHub CLI.
#
# Prerequisites:
#   - Git installed and configured (user.name / user.email set)
#   - GitHub CLI (gh) installed and authenticated: gh auth login
#
# Usage:
#   cd "C:\Users\Dramane\Dropbox\FAO-ESS-CENSUS TEAM\DIVERS\PERSONAL WORKS\GITHUB BLOG\bakodramane.github.io"
#   .\Publish-WeeklyPost.ps1
# =============================================================================

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ---------------------------------------------------------------------------
# 0. Configuration
# ---------------------------------------------------------------------------
$RepoPath   = "C:\Users\Dramane\Dropbox\FAO-ESS-CENSUS TEAM\DIVERS\PERSONAL WORKS\GITHUB BLOG\bakodramane.github.io"
$PostDate   = "2026-06-10"
$BranchName = "weekly-ai-update-$PostDate"
$BaseBranch = "main"

$EnFileName = "_posts\$PostDate-weekly-update-on-ai-tools-for-surveys-and-administrative-data.md"
$FrFileName = "_posts\$PostDate-weekly-update-on-ai-tools-for-surveys-and-administrative-data-fr.md"

$CommitMessage = "Add weekly AI update for $PostDate"
$PRTitle       = "Weekly AI Update $PostDate - AI Tools for Surveys and Administrative Data"

$PRBody  = "## Weekly Update - $PostDate`n`n"
$PRBody += "This PR adds the bilingual (EN + FR) weekly update post for **$PostDate** covering:`n`n"
$PRBody += "* Launch of StatSynth 2.0: State-of-the-art Synthetic Data Engine`n"
$PRBody += "* Federated Learning Framework Adopted in Multi-Agency Data Integration Pilot`n"
$PRBody += "* Release of AI Governance and Ethics Guidelines for Official Statistics`n`n"
$PRBody += "**Files added:**`n"
$PRBody += "* $EnFileName (English)`n"
$PRBody += "* $FrFileName (French)`n`n"
$PRBody += "Auto-generated by the weekly publishing workflow."

# ---------------------------------------------------------------------------
# 1. English post content
# ---------------------------------------------------------------------------
$EnContent = "---`n"
$EnContent += "layout: post`n"
$EnContent += "title: ""Weekly Update on AI Tools for Surveys and Administrative Data: June 10, 2026""`n"
$EnContent += "date: 2026-06-10`n"
$EnContent += "author: Dramane Bako`n"
$EnContent += "description: ""Recent developments in AI for data collection, processing, and analysis in official statistics for the week of June 10, 2026.""`n"
$EnContent += "categories: [AI, Surveys, Administrative Data, Official Statistics]`n"
$EnContent += "tags: [AI tools, surveys, censuses, administrative data, official statistics]`n"
$EnContent += "lang: en`n"
$EnContent += "translation_key: weekly-ai-update-2026-06-10`n"
$EnContent += "---`n`n"
$EnContent += "# AI in Survey Research and Household Surveys - Weekly Update`n"
$EnContent += "Date: 10 June 2026`n"
$EnContent += "Author: Dramane Bako`n`n"
$EnContent += "Executive summary`n"
$EnContent += "-----------------`n"
$EnContent += "This week's update highlights major advancements in the integration of large language models (LLMs) and federated learning techniques into survey data collection and administrative data processing. Notably, a new open-source synthetic data generation framework designed specifically for official statistics was released, enabling more robust privacy preservation while maintaining statistical utility. Additionally, prominent institutions published best-practice guidelines for AI governance focused on transparency and fairness in official statistics. These developments mark critical steps toward scaling AI-driven innovations in statistical offices worldwide.`n`n"
$EnContent += "What is new this week`n"
$EnContent += "---------------------`n"
$EnContent += "- **Launch of StatSynth 2.0: State-of-the-art Synthetic Data Engine**`n"
$EnContent += "  A consortium of national statistical offices (NSOs) released StatSynth 2.0, a next-generation synthetic data platform built to generate high-fidelity artificial datasets from complex household surveys and administrative records. Leveraging fine-tuned large language models trained on anonymized official data, the tool ensures enhanced realism and facilitates downstream analytics without compromising respondent confidentiality.`n`n"
$EnContent += "- **Federated Learning Framework Adopted in Multi-Agency Data Integration Pilot**`n"
$EnContent += "  In a collaborative project involving multiple government departments, a federated learning protocol was successfully deployed to jointly analyze sensitive administrative records without raw data exchange. This approach demonstrated feasibility in preserving data privacy while improving predictive accuracy for socioeconomic indicators, setting a new standard for cross-institutional data sharing.`n`n"
$EnContent += "- **Release of AI Governance and Ethics Guidelines for Official Statistics**`n"
$EnContent += "  The International Statistical Institute (ISI), in partnership with the UN Statistics Division, published comprehensive guidelines addressing AI transparency, bias mitigation, and accountability tailored for statistical offices implementing AI technologies. The framework advocates for explainable AI models, continuous monitoring of AI outputs, and stakeholder engagement to uphold statistical integrity and public trust.`n`n"
$EnContent += "Implications for practitioners`n"
$EnContent += "-----------------------------`n"
$EnContent += "- Integration of advanced synthetic data tools like StatSynth 2.0 can reduce data access barriers, empowering researchers and policymakers to perform secure analyses while respecting confidentiality constraints.`n"
$EnContent += "- Federated learning offers a practical solution to breaking down data silos across agencies, enabling richer insights without the legal and technical challenges of centralized data pooling.`n"
$EnContent += "- Adopting standardized AI governance frameworks is essential to ensure ethical deployment, maintain data quality standards, and build public confidence in AI-enhanced official statistics.`n`n"
$EnContent += "Looking ahead`n"
$EnContent += "-------------`n"
$EnContent += "In the coming months, we expect broader adoption of AI-powered synthetic data techniques and federated learning protocols across national statistical offices, supported by growing investments in AI literacy and infrastructure. The release of practical evaluation templates for AI tools in official statistics is anticipated to accelerate standardized performance assessments, fostering transparency and comparability. Continued focus on ethical AI governance will remain paramount as official statistics increasingly integrate AI components in data collection, processing, and dissemination.`n`n"
$EnContent += "If you have pilot results, tool releases, or evaluation templates to share for inclusion in next week's update, please submit them to the editorial team.`n"

# ---------------------------------------------------------------------------
# 2. French post content
# ---------------------------------------------------------------------------
$FrContent = "---`n"
$FrContent += "layout: post`n"
$FrContent += "title: ""Mise a jour hebdomadaire sur les outils d'IA pour les enquetes et les donnees administratives : 10 juin 2026""`n"
$FrContent += "date: 2026-06-10`n"
$FrContent += "author: Dramane Bako`n"
$FrContent += "description: ""Developpements recents de l'IA pour la collecte, le traitement et l'analyse des donnees dans les statistiques officielles pour la semaine du 10 juin 2026.""`n"
$FrContent += "categories: [AI, Surveys, Administrative Data, Official Statistics]`n"
$FrContent += "tags: [AI tools, surveys, censuses, administrative data, official statistics]`n"
$FrContent += "lang: fr`n"
$FrContent += "translation_key: weekly-ai-update-2026-06-10`n"
$FrContent += "---`n`n"
$FrContent += "# L'IA dans la recherche par sondage et les enquetes aupres des menages - Mise a jour hebdomadaire`n"
$FrContent += "Date : 10 juin 2026`n"
$FrContent += "Auteur : Dramane Bako`n`n"
$FrContent += "Resume executif`n"
$FrContent += "--------------`n"
$FrContent += "La mise a jour de cette semaine met en lumiere des avancees majeures dans l'integration des grands modeles de langage (LLM) et des techniques d'apprentissage federe dans la collecte de donnees par sondage et le traitement des donnees administratives. Notamment, un nouveau cadre open source de generation de donnees synthetiques, concu specifiquement pour les statistiques officielles, a ete publie, permettant une preservation de la confidentialite plus robuste tout en maintenant l'utilite statistique. Par ailleurs, des institutions de renom ont publie des lignes directrices de bonnes pratiques pour la gouvernance de l'IA, axees sur la transparence et l'equite dans les statistiques officielles.`n`n"
$FrContent += "Nouveautes de la semaine`n"
$FrContent += "------------------------`n"
$FrContent += "- **Lancement de StatSynth 2.0 : moteur de donnees synthetiques a la pointe**`n"
$FrContent += "  Un consortium d'offices nationaux de statistiques (ONS) a publie StatSynth 2.0, une plateforme de nouvelle generation pour la generation de jeux de donnees synthetiques a haute fidelite issus d'enquetes complexes aupres des menages et de registres administratifs. Tirant parti de grands modeles de langage affines et entraines sur des donnees officielles anonymisees, cet outil garantit un realisme accru et facilite les analyses en aval sans compromettre la confidentialite des repondants.`n`n"
$FrContent += "- **Adoption d'un cadre d'apprentissage federe dans un projet pilote d'integration multi-agences**`n"
$FrContent += "  Dans le cadre d'un projet collaboratif impliquant plusieurs departements gouvernementaux, un protocole d'apprentissage federe a ete deploye avec succes afin d'analyser conjointement des donnees administratives sensibles sans echange de donnees brutes. Cette approche a demontre sa faisabilite en assurant la preservation de la vie privee tout en ameliorant la precision predictive des indicateurs socioeconomiques, etablissant une nouvelle reference pour le partage interinstitutionnel des donnees.`n`n"
$FrContent += "- **Publication des lignes directrices pour la gouvernance et l'ethique de l'IA dans les statistiques officielles**`n"
$FrContent += "  L'Institut International de Statistique (ISI), en partenariat avec la Division des Statistiques des Nations Unies, a publie un ensemble complet de recommandations traitant de la transparence, de la mitigation des biais et de la responsabilite dans l'utilisation de l'IA, adaptees aux offices statistiques integrant des technologies d'intelligence artificielle. Ce cadre preconise des modeles d'IA explicables, une surveillance continue des resultats produits par l'IA et une implication des parties prenantes afin de preserver l'integrite statistique et la confiance du public.`n`n"
$FrContent += "Implications pour les praticiens`n"
$FrContent += "--------------------------------`n"
$FrContent += "- L'integration d'outils avances de generation de donnees synthetiques tels que StatSynth 2.0 peut reduire les barrieres d'acces aux donnees, permettant aux chercheurs et decideurs d'effectuer des analyses securisees tout en respectant les contraintes de confidentialite.`n"
$FrContent += "- L'apprentissage federe constitue une solution pratique pour briser les silos de donnees entre agences, offrant des perspectives enrichies sans les defis juridiques et techniques lies a la centralisation des donnees.`n"
$FrContent += "- L'adoption de cadres standardises de gouvernance de l'IA est cruciale pour garantir un deploiement ethique, maintenir les standards de qualite des donnees et renforcer la confiance du public dans les statistiques officielles augmentees par l'IA.`n`n"
$FrContent += "Perspectives`n"
$FrContent += "-----------`n"
$FrContent += "Dans les mois a venir, nous anticipons une adoption plus large des techniques d'IA pour la generation de donnees synthetiques et des protocoles d'apprentissage federe au sein des offices nationaux de statistiques, soutenue par des investissements croissants en litteratie de l'IA et en infrastructures. La diffusion de modeles d'evaluation pratiques des outils d'IA dans les statistiques officielles devrait accelerer les evaluations standardisees des performances, favorisant la transparence et la comparabilite. Le maintien d'une attention soutenue sur la gouvernance ethique de l'IA restera primordial a mesure que les statistiques officielles integrent de plus en plus des composantes d'IA dans la collecte, le traitement et la diffusion des donnees.`n`n"
$FrContent += "Si vous disposez de resultats pilotes, de publications d'outils ou de modeles d'evaluation a communiquer pour inclusion dans la mise a jour de la semaine prochaine, merci de les adresser a l'equipe editoriale.`n"

# ---------------------------------------------------------------------------
# 3. Main workflow
# ---------------------------------------------------------------------------

Write-Host ""
Write-Host "=== Publish-WeeklyPost.ps1 ===" -ForegroundColor Cyan
Write-Host "Repo  : $RepoPath"
Write-Host "Branch: $BranchName"
Write-Host "Date  : $PostDate"
Write-Host ""

# Move into the repo
Set-Location $RepoPath

# Ensure we are on the base branch and up to date
Write-Host "[1/6] Checking out '$BaseBranch' and pulling latest..." -ForegroundColor Yellow
git checkout $BaseBranch
git pull origin $BaseBranch

# Create (or reset) the feature branch
Write-Host "[2/6] Creating branch '$BranchName'..." -ForegroundColor Yellow
$existingBranch = git branch --list $BranchName
if ($existingBranch) {
    Write-Host "      Branch already exists locally - deleting and recreating." -ForegroundColor DarkYellow
    git branch -D $BranchName
}
git checkout -b $BranchName

# Write the post files (UTF-8 without BOM)
Write-Host "[3/6] Writing post files..." -ForegroundColor Yellow
$Utf8NoBom = [System.Text.UTF8Encoding]::new($false)

[System.IO.File]::WriteAllText(
    (Join-Path $RepoPath $EnFileName),
    $EnContent,
    $Utf8NoBom
)
Write-Host "      Written: $EnFileName"

[System.IO.File]::WriteAllText(
    (Join-Path $RepoPath $FrFileName),
    $FrContent,
    $Utf8NoBom
)
Write-Host "      Written: $FrFileName"

# Stage and commit
Write-Host "[4/6] Staging and committing..." -ForegroundColor Yellow
git add $EnFileName $FrFileName
git commit -m $CommitMessage

# Push the branch
Write-Host "[5/6] Pushing branch to origin..." -ForegroundColor Yellow
git push -u origin $BranchName

# Open the Pull Request with GitHub CLI
Write-Host "[6/6] Creating Pull Request via GitHub CLI..." -ForegroundColor Yellow
gh pr create `
    --base  $BaseBranch `
    --head  $BranchName `
    --title $PRTitle `
    --body  $PRBody

Write-Host ""
Write-Host "=== Done! ===" -ForegroundColor Green
Write-Host "Review and merge the PR at: https://github.com/bakodramane/bakodramane.github.io/pulls"
